### ISSUE TITLE
Usleep doesnt work correctly. 

### ISSUE THREAD

**Issue by shmidtelson** [bigperson/laravel-vk-geo#5]
https://github.com/bigperson/laravel-vk-geo/blob/f29d3cf73d8f8b8018f71f34ba4390b33b48e924/src/Commands/ImportCitiesCommand.php#L117

I am testing sleep, this worked for me. Maybe needs edit settings webserver?

**Comment by bigperson** [comment]
This function is used to not exceed the number of requests for api.

**Comment by bigperson** [comment]
You can try to change the delay in config
